### ISSUE TITLE
How can I redirect back to the app

### ISSUE THREAD

**Issue by Patiyang** [phanvantai/public_address_wallet#1]
i'm able to verify the metamask address but I have to navigate back to my app manually. Is there a way that it can go back automaticaly?

**Comment by phanvantai** [comment]
> i'm able to verify the metamask address but I have to navigate back to my app manually. Is there a way that it can go back automaticaly?

Sorry about that, last time I check, metamask mobile does not support that.

**Comment by phanvantai** [comment]
Metamask has automatically reopened the app after successful confirmation
